import {describe,expect,it} from 'vitest';
import {applyAction,createInitialState,getLegalAttackTargets,migrateGameState} from './engine';
import type {GameState} from './model';

function combatState(seed=1,kind:'party'|'base'='party'):GameState{let s=createInitialState(seed);s=applyAction(s,{type:'resolveEvent'});const red=s.players.red,blue=s.players.blue,origin=s.tiles.find(t=>t.id===red.baseTileId)!,target=s.tiles.find(t=>Math.abs(t.x-origin.x)+Math.abs(t.y-origin.y)===1)!;target.terrain='buildings';red.survivors=red.idlers=20;blue.survivors=blue.idlers=20;red.resources.weapons=blue.resources.weapons=20;s.parties=[{id:'red-party',ownerId:'red',tileId:origin.id,survivors:20,movesLeft:5}];red.idlers=0;if(kind==='party'){s.parties.push({id:'blue-party',ownerId:'blue',tileId:target.id,survivors:20,movesLeft:5});blue.idlers=0}else{const base=s.tiles.find(t=>t.id===blue.baseTileId)!.buildings.find(b=>b.type==='base')!;s.tiles.find(t=>t.id===blue.baseTileId)!.buildings=[];base.ownerId='blue';target.buildings.push(base);blue.baseTileId=target.id;}return s}
function start(s:GameState,targetId?:string,weapons=0,defenderWeapons=0){const target=getLegalAttackTargets(s,'red-party').find(t=>!targetId||t.targetId===targetId)!;return applyAction(s,{type:'startCombat',partyId:'red-party',targetId:target.targetId,people:20,weapons,defenderWeapons})}

describe('deterministic prototype combat policy',()=>{
 it('finds only adjacent enemy parties, buildings, and bases from the current party',()=>{const s=combatState();const targets=getLegalAttackTargets(s,'red-party');expect(targets).toEqual(expect.arrayContaining([expect.objectContaining({kind:'party',targetId:'blue-party'})]));s.parties[1].tileId=s.players.blue.baseTileId;expect(getLegalAttackTargets(s,'red-party')).toHaveLength(0)});
 it('rolls four attacker and two defender dice normally using state RNG',()=>{const before=start(combatState(42));const after=applyAction(before,{type:'rollCombat'});expect(after.battle?.history[0].attackerDice).toHaveLength(4);expect(after.battle?.history[0].defenderDice).toHaveLength(2);expect(after.rng).not.toBe(before.rng);expect(applyAction(before,{type:'rollCombat'}).battle?.history[0]).toEqual(after.battle?.history[0])});
 it('rolls three each on inferred open ground and makes tied comparisons kill both',()=>{let found:GameState|undefined;for(let seed=1;seed<500&&!found;seed++){const s=combatState(seed),target=getLegalAttackTargets(s,'red-party')[0];s.tiles.find(t=>t.id===target.tileId)!.terrain='grass';const rolled=applyAction(start(s),{type:'rollCombat'});const r=rolled.battle!.history[0];if(r.attackerDice.some((die,i)=>die===r.defenderDice[i]))found=rolled}expect(found?.battle?.history[0].attackerDice).toHaveLength(3);expect(found?.battle?.history[0].defenderDice).toHaveLength(3);const r=found!.battle!.history[0];const ties=r.attackerDice.filter((die,i)=>die===r.defenderDice[i]).length;expect(r.attackerCasualties).toBeGreaterThanOrEqual(ties);expect(r.defenderCasualties).toBeGreaterThanOrEqual(ties)});
 it('spreads committed weapons over dice, breaks used weapons, and applies a nearby ready tower to the highest die',()=>{let s=combatState(8);const origin=s.tiles.find(t=>t.id===s.players.red.baseTileId)!;origin.buildings.push({id:'tower',type:'watchtower',ownerId:'red',readyRound:s.round});s=start(s,undefined,6,0);const rolled=applyAction(s,{type:'rollCombat'}),record=rolled.battle!.history[0];expect(record.attackerWeaponsUsed).toBe(4);expect(record.attackerTower).toBe(true);expect(rolled.battle!.attacker.remainingWeapons).toBe(2);expect(s.players.red.resources.weapons).toBe(14)});
 it('blocks base retreat while allowing an attacking party to retreat and resolve',()=>{let base=start(combatState(4,'base'));expect(()=>applyAction(base,{type:'retreatCombat',side:'defender'})).toThrow(/Base defenders/);base=applyAction(base,{type:'retreatCombat',side:'attacker'});base=applyAction(base,{type:'resolveCombat'});expect(base.battle).toBeUndefined();expect(base.parties.find(p=>p.id==='red-party')?.tileId).toBe(base.players.red.baseTileId)});
 it('pauses after ten throws, resumes, and remains JSON serializable',()=>{let s=combatState(5);s.players.red.survivors=s.parties[0].survivors=100;s.players.blue.survivors=s.parties[1].survivors=100;s=start(s);for(let i=0;i<10;i++)s=applyAction(s,{type:'rollCombat'});expect(s.battle).toMatchObject({status:'paused',round:10,roundsSinceResume:10});const saved=migrateGameState(JSON.parse(JSON.stringify(s)))!;expect(saved.battle).toEqual(s.battle);s=applyAction(saved,{type:'resumeCombat'});expect(s.battle).toMatchObject({status:'active',roundsSinceResume:0})});
 it('captures an undefended enemy building and returns unspent friendly weapons',()=>{let s=combatState(10);const origin=s.tiles.find(t=>t.id===s.players.red.baseTileId)!,target=s.tiles.find(t=>Math.abs(t.x-origin.x)+Math.abs(t.y-origin.y)===1)!;s.parties=s.parties.filter(p=>p.ownerId==='red');target.buildings.push({id:'enemy-well',type:'well',ownerId:'blue',readyRound:1});s=start(s,'enemy-well',3,0);expect(s.battle?.status).toBe('attackerWon');s=applyAction(s,{type:'resolveCombat'});expect(target.id&&s.tiles.find(t=>t.id===target.id)?.buildings.find(b=>b.id==='enemy-well')?.ownerId).toBe('red');expect(s.players.red.resources.weapons).toBe(20)});
});
