import { describe, expect, it } from 'vitest';
import { applyAction, createInitialState } from './engine';

const toActivities=(seed=1,scavengers=0)=>{let s=createInitialState(seed);s=applyAction(s,{type:'resolveEvent'});s=applyAction(s,{type:'declareScavengers',count:scavengers});s=applyAction(s,{type:'resolvePlayerCard'});return applyAction(s,{type:'produce'});};
describe('deterministic engine',()=>{
 it('creates identical games from the same seed',()=>expect(createInitialState(42)).toEqual(createInitialState(42)));
 it('uses the workbook starting balance',()=>expect(createInitialState(1).players.red.resources).toMatchObject({water:9,food:9,medicines:4,rock:4,wood:4,tools:5,weapons:0,information:5}));
 it('follows event, declaration, card, production, activity, consumption phases',()=>{let s=toActivities();expect(s.phase).toBe('activities');s=applyAction(s,{type:'endActivities'});s=applyAction(s,{type:'consumeAndEndTurn'});expect(s.currentPlayerId).toBe('blue');expect(s.phase).toBe('declare');});
 it('grants one activity per three non-scavengers, rounded up',()=>{const s=toActivities(3,1);expect(s.activityLimit).toBe(1);});
 it('rejects gathering by more than three workers',()=>{const s=toActivities();expect(()=>applyAction(s,{type:'gather',tileId:s.players.red.baseTileId,survivors:4})).toThrow(/1–3/);});
 it('does not mutate prior state',()=>{const s=createInitialState(4),before=structuredClone(s);applyAction(s,{type:'resolveEvent'});expect(s).toEqual(before);});
 it('turns a found-building card into a free placement',()=>{let s=createInitialState(8);s.phase='card';s.players.red.currentCardId='p-well';s=applyAction(s,{type:'resolvePlayerCard'});s=applyAction(s,{type:'produce'});const before=s.players.red.resources;s=applyAction(s,{type:'placeFoundBuilding',tileId:s.players.red.baseTileId});expect(s.tiles.find(t=>t.id===s.players.red.baseTileId)?.buildings.some(b=>b.type==='well')).toBe(true);expect(s.players.red.resources).toEqual(before);});
 it('lets a player choose workshop output',()=>{const s=applyAction(createInitialState(9),{type:'setWorkshopOutput',resource:'weapons'});expect(s.players.red.workshopOutput).toBe('weapons');});
 it('uses tools held before payment to set construction timing and never activates on the build round',()=>{let s=toActivities(12);s.players.red.survivors=3;s.players.red.wounded=0;s.players.red.idlers=3;const base=s.players.red.baseTileId;s=applyAction(s,{type:'build',tileId:base,building:'well'});expect(s.tiles.find(t=>t.id===base)?.buildings.at(-1)?.readyRound).toBe(2);let slow=toActivities(13);slow.players.red.survivors=3;slow.players.red.wounded=0;slow.players.red.idlers=3;slow.players.red.resources.tools=1;slow=applyAction(slow,{type:'build',tileId:slow.players.red.baseTileId,building:'waterCleaner'});expect(slow.tiles.find(t=>t.id===slow.players.red.baseTileId)?.buildings.at(-1)?.readyRound).toBe(3);});
 it('does not produce from a new structure until its activation round',()=>{let s=toActivities(14);s.players.red.survivors=3;s.players.red.wounded=0;s.players.red.idlers=3;const base=s.players.red.baseTileId;s=applyAction(s,{type:'build',tileId:base,building:'well'});const water=s.players.red.resources.water;s.phase='production';s=applyAction(s,{type:'produce'});expect(s.players.red.resources.water).toBe(water);s.round=2;s.phase='production';s=applyAction(s,{type:'produce'});expect(s.players.red.resources.water).toBe(water+15);});
 it('gathers a relevant tile through an owned ready building on an adjacent tile',()=>{let s=toActivities(15);const base=s.tiles.find(t=>t.id===s.players.red.baseTileId)!;const target=s.tiles.find(t=>t.terrain==='wood'&&Math.abs(t.x-base.x)+Math.abs(t.y-base.y)>2)!;const support=s.tiles.find(t=>Math.abs(t.x-target.x)+Math.abs(t.y-target.y)===1)!;support.buildings.push({id:'camp',type:'lumberCamp',ownerId:'red',readyRound:1});const wood=s.players.red.resources.wood;s=applyAction(s,{type:'gather',tileId:target.id,survivors:1});expect(s.players.red.resources.wood).toBe(wood+1);});
 it('rejects remote gathering without a relevant ready building',()=>{const s=toActivities(16);const base=s.tiles.find(t=>t.id===s.players.red.baseTileId)!;const target=s.tiles.find(t=>Math.abs(t.x-base.x)+Math.abs(t.y-base.y)>2)!;expect(()=>applyAction(s,{type:'gather',tileId:target.id,survivors:1})).toThrow(/gathering building/);});
 it('spends information to peek deterministically and clears that peek when the card is drawn',()=>{let s=createInitialState(17);const next=s.decks.player.draw.at(-1)!;s=applyAction(s,{type:'peekNextCard',playerId:'blue',deck:'player'});expect(s.players.blue.resources.information).toBe(2);expect(s.peeks.blue.player).toBe(next);s=applyAction(s,{type:'resolveEvent'});s=applyAction(s,{type:'declareScavengers',count:0});expect(s.peeks.blue.player).toBeUndefined();});
 it('supports the authoritative optional finite-deck points ending',()=>{let s=createInitialState(18,'finiteDecks');s.phase='declare';s.decks.player.draw=['p-accident'];s.players.red.points=2;s.players.blue.points=5;s=applyAction(s,{type:'declareScavengers',count:0});expect(s.phase).toBe('gameOver');expect(s.winnerIds).toEqual(['blue']);});
 it('advances through a complete two-player round',()=>{let s=toActivities(19);s=applyAction(s,{type:'endActivities'});s=applyAction(s,{type:'consumeAndEndTurn'});s=applyAction(s,{type:'declareScavengers',count:0});s=applyAction(s,{type:'resolvePlayerCard'});s=applyAction(s,{type:'produce'});s=applyAction(s,{type:'endActivities'});s=applyAction(s,{type:'consumeAndEndTurn'});expect(s).toMatchObject({round:2,currentPlayerId:'red',phase:'event'});});
 it('rebuilds bases and removes parties whose tiles no longer exist on map import',()=>{let s=createInitialState(20);s.parties.push({id:'old',ownerId:'red',tileId:'99-99',survivors:1,movesLeft:5});s=applyAction(s,{type:'replaceMap',terrain:[['grass','grass'],['grass','grass']]});expect(s.parties).toEqual([]);expect(s.tiles.flatMap(t=>t.buildings).filter(b=>b.type==='base')).toHaveLength(2);});
 it('applies one death for a medicine shortage rather than one per untreated wound',()=>{let s=toActivities(21);s.players.red.survivors=5;s.players.red.wounded=3;s.players.red.resources={...s.players.red.resources,water:20,food:20,medicines:0};s.phase='consumption';s=applyAction(s,{type:'consumeAndEndTurn'});expect(s.players.red.survivors).toBe(4);expect(s.players.red.wounded).toBe(3);});
});
