import { BUILDINGS, CARDS, SAN_SEBASTIAN, STARTING_RESOURCES, TERRAIN, emptyResources } from './data';
import { RESOURCE_KEYS } from './model';
import type { Action, AttackTarget, BattleSide, BuildingType, Card, CombatRoll, Deck, GameState, Player, PlayerId, ResourceChange, Resources, Terrain, Tile, TurnRecord, WorkerAllocation } from './model';

const clone=<T>(x:T):T=>structuredClone(x);
function random(state:GameState){ state.rng=(Math.imul(state.rng,1664525)+1013904223)>>>0; return state.rng/4294967296; }
function shuffle(state:GameState,ids:string[]){ for(let i=ids.length-1;i>0;i--){const j=Math.floor(random(state)*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];} return ids; }
function draw(state:GameState,kind:'event'|'player'){ const deck=state.decks[kind]; if(!deck.draw.length&&state.endMode==='lastStanding'){deck.draw=shuffle(state,[...deck.discard]);deck.discard=[];} const id=deck.draw.pop();if(id){deck.discard.push(id);for(const peek of Object.values(state.peeks))delete peek[kind];}return id; }
function log(s:GameState,text:string){s.log.unshift(text);s.log=s.log.slice(0,80);}
function player(s:GameState){return s.players[s.currentPlayerId];}
function tile(s:GameState,id:string){const t=s.tiles.find(x=>x.id===id);if(!t)throw new Error('Tile not found.');return t;}
function assertPhase(s:GameState,p:GameState['phase']){if(s.phase!==p)throw new Error(`Expected ${p} phase, currently ${s.phase}.`);}
function spend(p:Player,cost:Partial<Resources>){for(const [k,v] of Object.entries(cost) as [keyof Resources,number][])if(p.resources[k]<v)throw new Error(`Not enough ${k}.`);for(const [k,v] of Object.entries(cost) as [keyof Resources,number][])p.resources[k]-=v;}
function createTiles(map:Terrain[][]):Tile[]{return map.flatMap((row,y)=>row.map((terrain,x)=>({id:`${x}-${y}`,x,y,terrain,buildings:[],depleted:{}})));}
function deckFor(kind:'event'|'player'):Deck{return {draw:CARDS.filter(c=>c.deck===kind).flatMap(c=>Array(c.copies).fill(c.id)),discard:[]};}
function placeBases(s:GameState){const candidates=s.tiles.filter(t=>TERRAIN[t.terrain].traversable);if(candidates.length<s.playerOrder.length)throw new Error('Map needs at least one traversable tile per player.');const positions=[candidates[Math.floor(candidates.length*.35)],candidates[Math.floor(candidates.length*.78)]];s.playerOrder.forEach((id,i)=>{const t=positions[i]??candidates[i];s.players[id].baseTileId=t.id;t.buildings.push({id:`base-${id}`,type:'base',ownerId:id,readyRound:1});});}
const changes=(before:Resources,after:Resources):ResourceChange[]=>RESOURCE_KEYS.flatMap(resource=>before[resource]===after[resource]?[]:[{resource,amount:after[resource]-before[resource]}]);
function eventRecord(s:GameState,resolved=false){const id=s.currentEventId;if(!id)return undefined;const c=s.cards[id];return {cardId:id,name:c.name,description:c.description,resolved};}
function newTurnRecord(s:GameState,playerId:PlayerId,eventResolved:boolean):TurnRecord{return {round:s.round,turn:s.turn,playerId,event:eventRecord(s,eventResolved),activities:[],completed:false};}
function partyWorkers(s:GameState,playerId:PlayerId){return s.parties.filter(x=>x.ownerId===playerId).reduce((n,x)=>n+x.survivors,0);}
function beginPlayerTurn(s:GameState){const p=player(s);p.currentCardId=draw(s,'player');if(finiteDeckCheck(s))return;if(p.currentCardId){const c=s.cards[p.currentCardId];s.currentTurn.playerCard={cardId:c.id,name:c.name,description:c.description,resolved:false};log(s,`${p.name} revealed ${c.name}.`);}s.activityUsed=0;s.activityLimit=Math.ceil(Math.max(0,p.idlers)/3);s.workflow={cardAcknowledged:false,scavenged:false,produced:false};s.phase='activities';}

export function getWorkerAllocation(s:GameState,playerId=s.currentPlayerId):WorkerAllocation{const p=s.players[playerId],parties=partyWorkers(s,playerId),usedThisTurn=Math.max(0,p.survivors-p.wounded-p.scavengers-p.idlers-parties);return {total:p.survivors,wounded:p.wounded,scavenging:p.scavengers,idle:p.idlers,usedThisTurn,parties,accounted:p.wounded+p.scavengers+p.idlers+usedThisTurn+parties};}

export function migrateGameState(raw:unknown):GameState|null{if(!raw||typeof raw!=='object')return null;const s=clone(raw as GameState);if(!s.players||!s.playerOrder||!s.cards||!s.decks||!s.tiles)return null;for(const p of Object.values(s.players)){p.workshopOutput??='tools';}s.endMode??='lastStanding';s.peeks??=Object.fromEntries(s.playerOrder.map(id=>[id,{}]));s.turnHistory=Array.isArray(s.turnHistory)?s.turnHistory.slice(-8):[];s.currentTurn=s.currentTurn??newTurnRecord(s,s.currentPlayerId,s.phase!=='event');s.currentTurn.activities??=[];s.workflow??={cardAcknowledged:s.phase!=='card'&&s.phase!=='declare',scavenged:s.currentTurn.scavengers!==undefined,produced:!!s.currentTurn.production};if(s.phase!=='event'&&s.phase!=='gameOver'&&s.phase!=='consumption'){const p=s.players[s.currentPlayerId];if(!p.currentCardId){p.currentCardId=draw(s,'player');const c=p.currentCardId?s.cards[p.currentCardId]:undefined;if(c)s.currentTurn.playerCard={cardId:c.id,name:c.name,description:c.description,resolved:false};}s.phase='activities';s.activityLimit=Math.max(s.activityLimit||0,Math.ceil(Math.max(0,p.idlers)/3));}for(const record of s.turnHistory)if(record.playerCard&&record.playerCard.resolved===undefined)record.playerCard.resolved=true;s.version=3;return s;}

export function createInitialState(seed=20221031,endMode:GameState['endMode']='lastStanding'):GameState{
 const cards=Object.fromEntries(CARDS.map(c=>[c.id,c]));
 const players:Record<string,Player>={red:{id:'red',name:'Red Refuge',color:'#e85d4a',survivors:3,wounded:0,idlers:3,scavengers:0,resources:{...STARTING_RESOURCES},baseTileId:'',points:0,workshopOutput:'tools'},blue:{id:'blue',name:'Blue Haven',color:'#4a91c7',survivors:3,wounded:0,idlers:3,scavengers:0,resources:{...STARTING_RESOURCES},baseTileId:'',points:0,workshopOutput:'tools'}};
 const s={} as GameState;Object.assign(s,{version:3,seed,rng:seed>>>0,round:1,turn:1,playerOrder:['red','blue'],currentPlayerId:'red',phase:'event',players,tiles:createTiles(SAN_SEBASTIAN),parties:[],cards,decks:{event:deckFor('event'),player:deckFor('player')},activityUsed:0,activityLimit:1,workflow:{cardAcknowledged:false,scavenged:false,produced:false},winnerIds:[],log:[],nextId:1,endMode,peeks:{red:{},blue:{}},turnHistory:[]});
 shuffle(s,s.decks.event.draw);shuffle(s,s.decks.player.draw);placeBases(s);s.currentEventId=draw(s,'event');s.currentTurn=newTurnRecord(s,'red',false);log(s,`Round 1 — ${cards[s.currentEventId!].name}.`);return s;
}

function applyCardEffect(s:GameState,card:Card,p?:Player){const targets=p?[p]:Object.values(s.players);const e=card.effect;
 if(e.type==='none')return;
 if(e.type==='gainAll')targets.forEach(x=>x.resources[e.resource]+=e.amount);
 if(e.type==='loseAll')targets.forEach(x=>Object.entries(e.amounts).forEach(([k,v])=>x.resources[k as keyof Resources]=Math.max(0,x.resources[k as keyof Resources]-(v??0))));
 if(e.type==='woundHalf')targets.forEach(x=>x.wounded=Math.min(x.survivors,x.wounded+Math.floor(x.survivors/2)));
 if(e.type==='weather')s.weather=e.weather;
 if(!p)return;
 if(e.type==='scavenge'&&p.scavengers>0)p.resources[e.resource]+=e.base+e.perScavenger*p.scavengers;
 if(e.type==='scavengerWound'&&p.scavengers>0){p.scavengers--;p.wounded++;}
 if(e.type==='scavengerDeath'&&p.scavengers>0){p.scavengers--;p.survivors--;}
 if(e.type==='survivors'){const radios=s.tiles.flatMap(t=>t.buildings).filter(b=>b.ownerId===p.id&&b.type==='radio').length;p.survivors+=3+radios;}
 if(e.type==='foundBuilding')p.pendingFoundBuilding=e.building;
}
function production(s:GameState,p:Player){for(const b of s.tiles.flatMap(t=>t.buildings).filter(b=>b.ownerId===p.id&&b.readyRound<=s.round)){const output={...BUILDINGS[b.type].production};if(b.type==='workshop'){delete output.tools;output[p.workshopOutput]=5;}for(const [k,v] of Object.entries(output) as [keyof Resources,number][]){if(v<0&&p.resources[k]<-v)continue;p.resources[k]=Math.max(0,p.resources[k]+v);}}}
function finishCheck(s:GameState){const alive=s.playerOrder.filter(id=>s.players[id].survivors>0);if(alive.length<=1){s.phase='gameOver';s.winnerIds=alive;log(s,alive.length?`${s.players[alive[0]].name} is the last party standing.`:'All parties perished.');return true;}return false;}
function finiteDeckCheck(s:GameState){if(s.endMode!=='finiteDecks'||(s.decks.event.draw.length&&s.decks.player.draw.length))return false;const alive=s.playerOrder.filter(id=>s.players[id].survivors>0);const best=Math.max(...alive.map(id=>s.players[id].points));s.winnerIds=alive.filter(id=>s.players[id].points===best);s.phase='gameOver';log(s,s.winnerIds.length===1?`${s.players[s.winnerIds[0]].name} wins on victory points.`:`The cards are finished; ${s.winnerIds.length} parties share the highest score.`);return true;}
const distance=(a:Tile,b:Tile)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function partyTileIsTraversable(s:GameState,t:Tile){return TERRAIN[t.terrain].traversable||(s.weather==='snow'&&t.terrain==='lake')||t.buildings.some(b=>b.type==='bridge')}
function partyRouteDistance(s:GameState,from:Tile,to:Tile){
 const tilesByPosition=new Map(s.tiles.map(t=>[`${t.x},${t.y}`,t])),visited=new Set([from.id]),queue:[Tile,number][]=[[from,0]];
 for(let index=0;index<queue.length;index++){
  const [current,steps]=queue[index];
  for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){
   const next=tilesByPosition.get(`${current.x+dx},${current.y+dy}`);
   if(!next||visited.has(next.id)||!partyTileIsTraversable(s,next))continue;
   if(next.id===to.id)return steps+1;
   visited.add(next.id);queue.push([next,steps+1]);
  }
 }
 return undefined;
}
function gatheringBuilding(s:GameState,p:Player,target:Tile){const suitable=(kind:BuildingType)=>kind==='quarry'||(kind==='farm'&&target.terrain==='grass')||((kind==='hunterCamp'||kind==='lumberCamp')&&target.terrain==='wood');return s.tiles.some(t=>distance(t,target)<=1&&t.buildings.some(b=>b.ownerId===p.id&&b.readyRound<=s.round&&suitable(b.type)));}

export function getLegalAttackTargets(s:GameState,partyId:string):AttackTarget[]{if(s.phase!=='activities'||s.battle)return[];const party=s.parties.find(candidate=>candidate.id===partyId&&candidate.ownerId===s.currentPlayerId);if(!party||party.movesLeft<1)return[];const origin=s.tiles.find(candidate=>candidate.id===party.tileId);if(!origin)return[];return s.tiles.filter(candidate=>distance(origin,candidate)===1).flatMap(candidate=>[
 ...s.parties.filter(enemy=>enemy.tileId===candidate.id&&enemy.ownerId!==party.ownerId).map(enemy=>({tileId:candidate.id,kind:'party' as const,targetId:enemy.id,ownerId:enemy.ownerId,label:`${s.players[enemy.ownerId]?.name??'Enemy'} party (${enemy.survivors})`})),
 ...candidate.buildings.filter(building=>building.ownerId!==party.ownerId).map(building=>({tileId:candidate.id,kind:building.type==='base'?'base' as const:'building' as const,targetId:building.id,ownerId:building.ownerId,label:`${s.players[building.ownerId]?.name??'Enemy'} ${building.type==='base'?'base':BUILDINGS[building.type].label}`}))
])}
const OPEN_GROUND:Terrain[]=['grass','rocks','sand'];
function hasTower(s:GameState,playerId:PlayerId,target:Tile){return s.tiles.some(candidate=>distance(candidate,target)<=1&&candidate.buildings.some(building=>building.ownerId===playerId&&building.type==='watchtower'&&building.readyRound<=s.round))}
function rollSide(s:GameState,count:number,weapons:number,tower:boolean){const dice=Array.from({length:count},()=>Math.floor(random(s)*6)+1),used=Math.min(weapons,dice.length);for(let i=0;i<used;i++)dice[i]++;dice.sort((a,b)=>b-a);if(tower&&dice.length)dice[0]++;return{dice,used}}
function settleBattleSide(s:GameState,side:BattleSide){const casualty=Math.min(side.casualties,side.committedPeople),party=side.partyId?s.parties.find(candidate=>candidate.id===side.partyId):undefined,p=s.players[side.playerId];p.survivors=Math.max(0,p.survivors-casualty);if(party)party.survivors=Math.max(0,party.survivors-casualty);else p.idlers=Math.max(0,p.idlers-casualty);if(party?.survivors===0)s.parties=s.parties.filter(candidate=>candidate.id!==party.id)}
function returnOrCaptureWeapons(s:GameState,winner:BattleSide|undefined,loser:BattleSide|undefined){if(!winner||!loser){for(const side of [winner,loser])if(side)s.players[side.playerId].resources.weapons+=side.remainingWeapons;return}const loserEliminated=loser.remainingPeople===0;if(loserEliminated)s.players[winner.playerId].resources.weapons+=loser.remainingWeapons;else s.players[loser.playerId].resources.weapons+=loser.remainingWeapons;s.players[winner.playerId].resources.weapons+=winner.remainingWeapons}

export function applyAction(input:GameState,action:Action):GameState{const s=clone(input),p=player(s);
 if(s.battle&&!['rollCombat','retreatCombat','resumeCombat','resolveCombat'].includes(action.type))throw new Error('Finish or pause the current combat first.');
 switch(action.type){
 case'resolveEvent':assertPhase(s,'event');if(s.currentEventId){const c=s.cards[s.currentEventId];applyCardEffect(s,c);s.currentTurn.event={cardId:c.id,name:c.name,description:c.description,resolved:true};log(s,`Resolved event: ${c.description}`);}beginPlayerTurn(s);break;
 case'resolvePlayerCard':if(s.phase==='card'){beginPlayerTurn(s);break;}throw new Error('The player card is already revealed.');
 case'acknowledgePlayerCard':assertPhase(s,'activities');s.workflow.cardAcknowledged=true;break;
 case'declareScavengers':assertPhase(s,'activities');if(s.workflow.scavenged)throw new Error('Scavengers already assigned this turn.');{const available=p.idlers;if(!Number.isInteger(action.count)||action.count<0||action.count>available)throw new Error(`Choose between 0 and ${available} idle survivors.`);p.scavengers=action.count;p.idlers=available-action.count;s.currentTurn.scavengers=action.count;if(p.currentCardId){const c=s.cards[p.currentCardId];applyCardEffect(s,c,p);s.currentTurn.playerCard={cardId:c.id,name:c.name,description:c.description,resolved:true};log(s,`${p.name}: ${c.name} — ${c.description}`);}s.workflow.scavenged=true;log(s,`${p.name} sends ${action.count} scavenger(s).`);}break;
 case'produce':assertPhase(s,'activities');if(s.workflow.produced)throw new Error('Production already completed this turn.');{const before={...p.resources};production(s,p);s.currentTurn.production=changes(before,p.resources);s.workflow.produced=true;log(s,`${p.name} production completed.`);}break;
 case'gather':assertPhase(s,'activities');if(s.activityUsed>=s.activityLimit)throw new Error('No activities remaining.');if(action.survivors<1||action.survivors>3||action.survivors>p.idlers)throw new Error('Gathering needs 1–3 idle survivors.');{const t=tile(s,action.tileId);const base=tile(s,p.baseTileId);if(distance(base,t)>1&&!gatheringBuilding(s,p,t))throw new Error('Gather directly beside your base or use a ready gathering building on or beside this tile.');const yields={...TERRAIN[t.terrain].yields};if(s.weather==='snow')delete yields.water;const gains=Object.entries(yields).map(([resource,amount])=>({resource:resource as keyof Resources,amount:(amount??0)*action.survivors}));for(const x of gains)p.resources[x.resource]+=x.amount;p.idlers-=action.survivors;s.activityUsed++;s.currentTurn.activities.push({type:'gather',tileId:t.id,terrain:t.terrain,survivors:action.survivors,gains});log(s,`${action.survivors} gathered at ${t.id} (${TERRAIN[t.terrain].label}).`);}break;
 case'build':assertPhase(s,'activities');if(s.activityUsed>=s.activityLimit)throw new Error('No activities remaining.');if(p.idlers<3)throw new Error('Building requires 3 idle survivors.');{const t=tile(s,action.tileId),d=BUILDINGS[action.building],hasCrewTools=p.resources.tools>=3;if(!TERRAIN[t.terrain].buildable&&action.building!=='bridge')throw new Error('Terrain is not buildable.');if(d.placement&&!d.placement.includes(t.terrain))throw new Error('Wrong terrain for this building.');spend(p,d.cost);const ready=s.round+(hasCrewTools?1:2);t.buildings.push({id:`b${s.nextId++}`,type:action.building,ownerId:p.id,readyRound:ready});p.idlers-=3;s.activityUsed++;s.currentTurn.activities.push({type:'build',tileId:t.id,building:action.building,survivors:3,readyRound:ready});log(s,`${p.name} started ${d.label}; ready in round ${ready}.`);}break;
 case'placeFoundBuilding':assertPhase(s,'activities');if(!p.pendingFoundBuilding)throw new Error('No found building is waiting for placement.');{const t=tile(s,action.tileId),kind=p.pendingFoundBuilding,d=BUILDINGS[kind],readyRound=s.round+1;if(kind==='bridge'&&t.terrain!=='lake')throw new Error('A bridge must be placed over water.');if(kind!=='bridge'&&!TERRAIN[t.terrain].buildable)throw new Error('Terrain is not buildable.');if(d.placement&&!d.placement.includes(t.terrain))throw new Error('Wrong terrain for this building.');t.buildings.push({id:`b${s.nextId++}`,type:kind,ownerId:p.id,readyRound});p.pendingFoundBuilding=undefined;s.currentTurn.activities.push({type:'foundBuilding',tileId:t.id,building:kind,readyRound});log(s,`${p.name} placed found ${d.label}.`);}break;
 case'setWorkshopOutput':p.workshopOutput=action.resource;log(s,`${p.name}'s workshops will produce ${action.resource}.`);break;
 case'peekNextCard':if(s.phase==='gameOver')throw new Error('The game is over.');{const viewer=s.players[action.playerId];if(!viewer)throw new Error('Player not found.');spend(viewer,{information:3});const id=s.decks[action.deck].draw.at(-1);if(!id)throw new Error(`No ${action.deck} card remains to inspect.`);s.peeks[viewer.id][action.deck]=id;s.currentTurn.activities.push({type:'intel',playerId:viewer.id,deck:action.deck,cardId:id});log(s,`${viewer.name} spent 3 information to inspect the next ${action.deck} card.`);}break;
 case'lookForSurvivors':assertPhase(s,'activities');if(s.activityUsed>=s.activityLimit)throw new Error('No activities remaining.');if(action.food<4||action.food>12||action.food%4)throw new Error('Invest 4, 8, or 12 food.');spend(p,{food:action.food});{const radios=s.tiles.flatMap(t=>t.buildings).filter(b=>b.ownerId===p.id&&b.type==='radio').length,found=action.food/4+radios;p.survivors+=found;p.idlers+=found;s.currentTurn.activities.push({type:'survivors',food:action.food,found});}s.activityUsed++;break;
 case'createParty':assertPhase(s,'activities');if(action.survivors<1||action.survivors>p.idlers)throw new Error('Invalid party size.');{const id=`p${s.nextId++}`;p.idlers-=action.survivors;s.parties.push({id,ownerId:p.id,tileId:p.baseTileId,survivors:action.survivors,movesLeft:5});s.currentTurn.activities.push({type:'partyCreated',partyId:id,survivors:action.survivors,tileId:p.baseTileId});}break;
 case'moveParty':assertPhase(s,'activities');{const party=s.parties.find(x=>x.id===action.partyId&&x.ownerId===p.id);if(!party)throw new Error('Party not found.');const from=tile(s,party.tileId),to=tile(s,action.tileId);if(from.id===to.id)throw new Error('Party already occupies that tile.');if(!partyTileIsTraversable(s,to))throw new Error('Destination is not traversable.');const routeDistance=partyRouteDistance(s,from,to);if(routeDistance===undefined)throw new Error('No traversable route reaches that destination.');if(routeDistance>party.movesLeft)throw new Error('Move exceeds remaining movement allowance.');party.tileId=to.id;party.movesLeft-=routeDistance;s.currentTurn.activities.push({type:'partyMoved',partyId:party.id,survivors:party.survivors,fromTileId:from.id,tileId:to.id,distance:routeDistance});}break;
 case'startCombat':assertPhase(s,'activities');{const party=s.parties.find(candidate=>candidate.id===action.partyId&&candidate.ownerId===p.id),target=getLegalAttackTargets(s,action.partyId).find(candidate=>candidate.targetId===action.targetId);if(!party||!target)throw new Error('That attack target is not adjacent and legal.');if(!Number.isInteger(action.people)||action.people<1||action.people>party.survivors)throw new Error('Commit between 1 and the party size.');if(!Number.isInteger(action.weapons)||action.weapons<0||action.weapons>action.people||action.weapons>p.resources.weapons)throw new Error('Attacker weapons cannot exceed committed people or available weapons.');const defender=s.players[target.ownerId],defenderParty=target.kind==='party'?s.parties.find(candidate=>candidate.id===target.targetId):undefined,defenderPeople=defenderParty?.survivors??(target.kind==='base'?defender.idlers:0);if(!Number.isInteger(action.defenderWeapons)||action.defenderWeapons<0||action.defenderWeapons>defenderPeople||action.defenderWeapons>defender.resources.weapons)throw new Error('Defender weapons cannot exceed defenders or available weapons.');const targetTile=tile(s,target.tileId);p.resources.weapons-=action.weapons;defender.resources.weapons-=action.defenderWeapons;party.movesLeft--;s.battle={id:`fight${s.nextId++}`,attacker:{playerId:p.id,partyId:party.id,committedPeople:action.people,remainingPeople:action.people,committedWeapons:action.weapons,remainingWeapons:action.weapons,casualties:0,towerBonus:hasTower(s,p.id,targetTile)},defender:{playerId:defender.id,partyId:defenderParty?.id,committedPeople:defenderPeople,remainingPeople:defenderPeople,committedWeapons:action.defenderWeapons,remainingWeapons:action.defenderWeapons,casualties:0,towerBonus:hasTower(s,defender.id,targetTile)},targetTileId:target.tileId,targetKind:target.kind,targetId:target.targetId,originTileId:party.tileId,openGround:OPEN_GROUND.includes(targetTile.terrain),round:0,roundsSinceResume:0,status:defenderPeople===0?'attackerWon':'active',history:[]};log(s,`${p.name} attacks ${target.label} at ${target.tileId}.`);}break;
 case'rollCombat':{const battle=s.battle;if(!battle||battle.status!=='active')throw new Error('Combat is not ready to roll.');const attackerCount=Math.min(battle.openGround?3:4,battle.attacker.remainingPeople),defenderCount=Math.min(battle.openGround?3:2,battle.defender.remainingPeople),attackerRoll=rollSide(s,attackerCount,battle.attacker.remainingWeapons,battle.attacker.towerBonus),defenderRoll=rollSide(s,defenderCount,battle.defender.remainingWeapons,battle.defender.towerBonus);battle.attacker.remainingWeapons-=attackerRoll.used;battle.defender.remainingWeapons-=defenderRoll.used;let attackerCasualties=0,defenderCasualties=0;for(let i=0;i<Math.min(attackerRoll.dice.length,defenderRoll.dice.length);i++){if(attackerRoll.dice[i]>defenderRoll.dice[i])defenderCasualties++;else if(attackerRoll.dice[i]<defenderRoll.dice[i])attackerCasualties++;else if(battle.openGround){attackerCasualties++;defenderCasualties++}else attackerCasualties++;}attackerCasualties=Math.min(attackerCasualties,battle.attacker.remainingPeople);defenderCasualties=Math.min(defenderCasualties,battle.defender.remainingPeople);battle.attacker.remainingPeople-=attackerCasualties;battle.defender.remainingPeople-=defenderCasualties;battle.attacker.casualties+=attackerCasualties;battle.defender.casualties+=defenderCasualties;battle.round++;battle.roundsSinceResume++;const record:CombatRoll={round:battle.round,attackerDice:attackerRoll.dice,defenderDice:defenderRoll.dice,attackerCasualties,defenderCasualties,attackerWeaponsUsed:attackerRoll.used,defenderWeaponsUsed:defenderRoll.used,attackerTower:battle.attacker.towerBonus,defenderTower:battle.defender.towerBonus};battle.history.push(record);if(!battle.defender.remainingPeople)battle.status='attackerWon';else if(!battle.attacker.remainingPeople)battle.status='defenderWon';else if(battle.roundsSinceResume>=10)battle.status='paused';log(s,`Combat round ${battle.round}: ${attackerRoll.dice.join(',')} vs ${defenderRoll.dice.join(',')}; losses ${attackerCasualties}/${defenderCasualties}.`);}break;
 case'retreatCombat':{const battle=s.battle;if(!battle||!['active','paused'].includes(battle.status))throw new Error('Combat cannot retreat now.');if(action.side==='defender'&&battle.targetKind==='base')throw new Error('Base defenders cannot retreat.');if(action.side==='defender'&&!battle.defender.partyId)throw new Error('Only a defending party can retreat.');battle.status=action.side==='attacker'?'attackerRetreated':'defenderRetreated';}break;
 case'resumeCombat':if(!s.battle||s.battle.status!=='paused')throw new Error('Only paused combat can resume.');s.battle.status='active';s.battle.roundsSinceResume=0;break;
 case'resolveCombat':{const battle=s.battle;if(!battle||['active','paused'].includes(battle.status))throw new Error('Combat must end before resolution.');settleBattleSide(s,battle.attacker);settleBattleSide(s,battle.defender);const attackerWon=['attackerWon','defenderRetreated'].includes(battle.status),defenderWon=['defenderWon','attackerRetreated'].includes(battle.status),winner=attackerWon?battle.attacker:defenderWon?battle.defender:undefined,loser=attackerWon?battle.defender:defenderWon?battle.attacker:undefined;returnOrCaptureWeapons(s,winner,loser);if(attackerWon){const attackingParty=s.parties.find(candidate=>candidate.id===battle.attacker.partyId);if(attackingParty)attackingParty.tileId=battle.targetTileId;if(battle.targetKind!=='party'){const building=tile(s,battle.targetTileId).buildings.find(candidate=>candidate.id===battle.targetId);if(building)building.ownerId=battle.attacker.playerId;}}s.currentTurn.activities.push({type:'combat',battleId:battle.id,targetTileId:battle.targetTileId,result:battle.status,rounds:battle.round});log(s,`Combat resolved: ${battle.status}.`);s.battle=undefined;finishCheck(s);}break;
 case'endActivities':assertPhase(s,'activities');if(!s.workflow.scavenged)throw new Error('Choose scavengers before ending the turn.');if(!s.workflow.produced)throw new Error('Run production before ending the turn.');s.phase='consumption';break;
 case'consumeAndEndTurn':assertPhase(s,'consumption');{const working=p.survivors-p.idlers;const waterNeed=p.survivors+(s.weather==='heat'?working:0),foodNeed=p.survivors;let deaths=0;if(p.resources.water<waterNeed)deaths++;if(p.resources.food<foodNeed)deaths++;const medicinesNeed=p.wounded,medicinesUsed=Math.min(p.wounded,p.resources.medicines),medicineShortage=medicinesUsed<p.wounded;if(medicineShortage)deaths++;s.currentTurn.consumption={waterNeed,foodNeed,medicinesNeed,medicinesUsed,deaths};s.currentTurn.completed=true;s.turnHistory=[...s.turnHistory,s.currentTurn].slice(-8);p.resources.water=Math.max(0,p.resources.water-waterNeed);p.resources.food=Math.max(0,p.resources.food-foodNeed);p.resources.medicines-=medicinesUsed;p.survivors=Math.max(0,p.survivors-deaths);p.wounded=Math.min(p.survivors,p.wounded-medicinesUsed);p.scavengers=0;p.idlers=Math.max(0,p.survivors-p.wounded-partyWorkers(s,p.id));log(s,`${p.name} consumed supplies${deaths?`; ${deaths} died`:''}.`);if(finishCheck(s))break;const index=s.playerOrder.indexOf(p.id);if(index===s.playerOrder.length-1){s.round++;s.weather=undefined;s.currentPlayerId=s.playerOrder[0];s.currentEventId=draw(s,'event');if(finiteDeckCheck(s))break;s.phase='event';s.turn++;s.currentTurn=newTurnRecord(s,s.currentPlayerId,false);s.workflow={cardAcknowledged:false,scavenged:false,produced:false};log(s,`Round ${s.round} — ${s.cards[s.currentEventId!].name}.`);}else{s.currentPlayerId=s.playerOrder[index+1];s.turn++;s.currentTurn=newTurnRecord(s,s.currentPlayerId,true);beginPlayerTurn(s);}s.parties.forEach(x=>x.movesLeft=5);}break;
 case'replaceMap':if(action.terrain.length<2||action.terrain[0].length<2||action.terrain.some(r=>r.length!==action.terrain[0].length))throw new Error('Invalid terrain grid.');s.tiles=createTiles(action.terrain);s.parties=[];placeBases(s);log(s,'Board rebuilt from a real-world map image; field parties returned to their new bases.');break;
 default: throw new Error('Unknown action.');}
 return s;
}
