import { useMemo, useRef, useState } from 'react';
import { BUILDINGS, TERRAIN } from '../game/data';
import { applyAction, createInitialState } from '../game/engine';
import { imageDataToTerrain } from '../game/mapConversion';
import { RESOURCE_KEYS, type Action, type BuildingType, type GameState } from '../game/model';

const SAVE='survivors-save-v1';
function load():GameState{try{const x=localStorage.getItem(SAVE);if(!x)return createInitialState();const s=JSON.parse(x) as GameState;for(const p of Object.values(s.players))p.workshopOutput??='tools';s.endMode??='lastStanding';s.peeks??=Object.fromEntries(s.playerOrder.map(id=>[id,{}]));return s;}catch{return createInitialState();}}

export function App(){
 const [state,setState]=useState(load);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [selected,setSelected]=useState('0-0');const [scavengers,setScavengers]=useState(0);const [workers,setWorkers]=useState(1);const [building,setBuilding]=useState<BuildingType>('well');const [intelViewer,setIntelViewer]=useState(state.currentPlayerId);const canvas=useRef<HTMLCanvasElement>(null);
 const current=state.players[state.currentPlayerId],viewer=state.players[intelViewer]??current,event=state.currentEventId?state.cards[state.currentEventId]:undefined,card=current.currentCardId?state.cards[current.currentCardId]:undefined;
 const dispatch=(action:Action)=>{try{const next=applyAction(state,action);setState(next);localStorage.setItem(SAVE,JSON.stringify(next));setError('');setNotice(action.type==='replaceMap'?'Map converted successfully.':'');}catch(e){setError(e instanceof Error?e.message:String(e));setNotice('');}};
 const cols=Math.max(...state.tiles.map(t=>t.x))+1;
 const selectedTile=state.tiles.find(t=>t.id===selected);
 const phaseAction=()=>{if(state.phase==='event')dispatch({type:'resolveEvent'});else if(state.phase==='declare')dispatch({type:'declareScavengers',count:scavengers});else if(state.phase==='card')dispatch({type:'resolvePlayerCard'});else if(state.phase==='production')dispatch({type:'produce'});else if(state.phase==='activities')dispatch({type:'endActivities'});else if(state.phase==='consumption')dispatch({type:'consumeAndEndTurn'});};
 const phaseLabel={event:'Resolve event',declare:'Confirm scavengers',card:'Resolve player card',production:'Run production',activities:'Finish activities',consumption:'Consume & end turn',gameOver:'Game over'}[state.phase];
 const onMap=async(file:File)=>{const img=new Image();img.src=URL.createObjectURL(file);await img.decode();const c=canvas.current!;c.width=img.width;c.height=img.height;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;dispatch({type:'replaceMap',terrain:imageDataToTerrain(data,c.width,c.height)});URL.revokeObjectURL(img.src);};
 const buildings=useMemo(()=>Object.entries(BUILDINGS).filter(([k])=>!['base','bridge'].includes(k)) as [BuildingType,typeof BUILDINGS[BuildingType]][],[]);
 return <main>
  <header><div><p className="eyebrow">POST-COLLAPSE STRATEGY</p><h1>Survivors</h1></div><div className="round">ROUND <strong>{state.round}</strong><span>{current.name}</span></div></header>
  <div className="sr-only" aria-live="polite">{error||notice}</div>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice">{notice}</div>}
  <section className="layout">
   <div className="board-panel">
    <div className="map-title"><div><h2>San Sebastián</h2><p>Real terrain converted from the prototype map</p></div><label className="upload">Convert another map<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&onMap(e.target.files[0])}/></label></div>
    <div className="board" aria-label="Terrain board" style={{gridTemplateColumns:`repeat(${cols}, minmax(28px,1fr))`}}>{state.tiles.map(t=><button key={t.id} type="button" aria-pressed={selected===t.id} aria-label={`${t.id}, ${TERRAIN[t.terrain].label}`} title={`${t.id} · ${TERRAIN[t.terrain].label}`} className={`tile ${selected===t.id?'selected':''}`} style={{background:TERRAIN[t.terrain].color}} onClick={()=>setSelected(t.id)}><span>{TERRAIN[t.terrain].letter}</span>{t.buildings.map(b=><img className={b.readyRound>state.round?'constructing':''} key={b.id} src={`/icons/${b.type}.png`} alt=""/>)}</button>)}</div>
    <div className="legend">{Object.entries(TERRAIN).map(([k,v])=><span key={k}><i style={{background:v.color}}/>{v.label}</span>)}</div>
   </div>
   <aside>
    <div className="phase"><span>TURN PHASE</span><h2>{state.phase.toUpperCase()}</h2>{state.phase==='event'&&event&&<CardView title="WORLD EVENT" name={event.name} text={event.description}/>} {state.phase==='card'&&card&&<CardView title="PLAYER CARD" name={card.name} text={card.description}/>} {state.phase==='declare'&&<label>Active scavengers<input type="number" min="0" max={current.survivors-current.wounded} value={scavengers} onChange={e=>setScavengers(+e.target.value)}/></label>}<button className="primary" disabled={state.phase==='gameOver'} onClick={phaseAction}>{phaseLabel}</button></div>
    <div className="party"><h3>{current.name}</h3><div className="people"><strong>{current.survivors}</strong> survivors · {current.wounded} wounded · {current.idlers} idle</div><div className="resources">{RESOURCE_KEYS.map(r=><div key={r}><span>{r}</span><strong>{current.resources[r]}</strong></div>)}</div><div className="intel"><label>Intel can be used outside a turn<select value={viewer.id} onChange={e=>setIntelViewer(e.target.value)}>{state.playerOrder.map(id=><option key={id} value={id}>{state.players[id].name}</option>)}</select></label><button disabled={viewer.resources.information<3} onClick={()=>dispatch({type:'peekNextCard',playerId:viewer.id,deck:'event'})}>Peek event · 3 info</button><button disabled={viewer.resources.information<3} onClick={()=>dispatch({type:'peekNextCard',playerId:viewer.id,deck:'player'})}>Peek player · 3 info</button>{Object.entries(state.peeks[viewer.id]??{}).map(([kind,id])=><CardView key={kind} title={`NEXT ${kind}`} name={state.cards[id].name} text={state.cards[id].description}/>)}</div></div>
    {state.phase==='activities'&&<div className="actions"><h3>Activities <small>{state.activityUsed}/{state.activityLimit}</small></h3><p>Selected: {selectedTile?`${TERRAIN[selectedTile.terrain].label} ${selected}`:'none'}. Gather beside your base or via a ready adjacent gathering building.</p>{current.pendingFoundBuilding&&<button className="found" onClick={()=>dispatch({type:'placeFoundBuilding',tileId:selected})}>Place free {BUILDINGS[current.pendingFoundBuilding].label}</button>}<label>Workers (1–3)<input type="number" min="1" max="3" value={workers} onChange={e=>setWorkers(+e.target.value)}/></label><button onClick={()=>dispatch({type:'gather',tileId:selected,survivors:workers})}>Gather</button><button onClick={()=>dispatch({type:'lookForSurvivors',food:4})}>Search (4 food)</button><label>Structure<select value={building} onChange={e=>setBuilding(e.target.value as BuildingType)}>{buildings.map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><button onClick={()=>dispatch({type:'build',tileId:selected,building})}>Build</button><label>Workshop output<select value={current.workshopOutput} onChange={e=>dispatch({type:'setWorkshopOutput',resource:e.target.value as 'tools'|'weapons'})}><option value="tools">5 tools</option><option value="weapons">5 weapons</option></select></label></div>}
   </aside>
  </section>
  <section className="lower"><div><h3>Field log</h3>{state.log.slice(0,7).map((x,i)=><p key={i}>{x}</p>)}</div><div><h3>How this table works</h3><p>Pass the device to the named refuge. Resolve the gold phase button from top to bottom, then use activities on a selected tile. Faded structures are still under construction.</p><p>Seed <code>{state.seed}</code> · deterministic RNG <code>{state.rng}</code></p><button onClick={()=>{const s=createInitialState();setState(s);localStorage.setItem(SAVE,JSON.stringify(s));setError('');}}>New game</button></div></section>
  <canvas ref={canvas} hidden/>
 </main>;
}
function CardView({title,name,text}:{title:string;name:string;text:string}){return <article className="card"><span>{title}</span><h3>{name}</h3><p>{text}</p></article>}
