import { useMemo, useRef, useState } from 'react';
import { BUILDINGS, TERRAIN } from '../game/data';
import { applyAction, createInitialState, getWorkerAllocation, migrateGameState } from '../game/engine';
import { imageDataToTerrain } from '../game/mapConversion';
import { RESOURCE_KEYS, type Action, type BuildingType, type GameState, type Resource, type Terrain, type TurnActivity, type TurnStep } from '../game/model';

const SAVE='survivors-save-v1', MAP_SAVE='survivors-map-presentation-v1', BUILT_IN_MAP='/maps/san-sebastian-terrain.jpg';
const TERRAIN_EMOJI:Record<Terrain,string>={lake:'🌊',swamp:'🐸',wood:'🌲',grass:'🌿',buildings:'🏙️',mountain:'⛰️',rocks:'🪨',sand:'🏖️'};
const RESOURCE_META:Record<Resource,{emoji:string;label:string}>={water:{emoji:'💧',label:'Water'},food:{emoji:'🥫',label:'Food'},medicines:{emoji:'💊',label:'Medicines'},rock:{emoji:'🪨',label:'Rock'},wood:{emoji:'🪵',label:'Wood'},tools:{emoji:'🛠️',label:'Tools'},weapons:{emoji:'⚔️',label:'Weapons'},information:{emoji:'📻',label:'Information'}};
const STEPS:{id:TurnStep;icon:string;label:string;help:string}[]=[
 {id:'event',icon:'⚠️',label:'World event',help:'Once each round, reveal and resolve a world event for every refuge. Then the active refuge declares scavengers.'},
 {id:'declare',icon:'🎒',label:'Scavengers',help:'Choose healthy, unassigned survivors to scavenge. They cannot work activities this turn. Then draw your player card.'},
 {id:'card',icon:'🃏',label:'Player card',help:'Resolve the active refuge’s card, including its scavenger effect. Then ready structures produce automatically.'},
 {id:'production',icon:'🏭',label:'Production',help:'Every owned structure ready this round produces its listed resources. Then choose your activities.'},
 {id:'activities',icon:'⚡',label:'Activities',help:'Spend activities to gather, build, search, or manage field parties. Workers used here stay used until turn end.'},
 {id:'consumption',icon:'🥫',label:'Consumption',help:'Pay one food and water per survivor, medicine for wounds, and heatwave water for workers. Then pass to the next refuge.'}
];
export function loadSavedState(value:string|null):GameState{try{return value?migrateGameState(JSON.parse(value))??createInitialState():createInitialState();}catch{return createInitialState();}}
function load():GameState{return loadSavedState(localStorage.getItem(SAVE));}
function loadMap(){try{return localStorage.getItem(MAP_SAVE)||BUILT_IN_MAP;}catch{return BUILT_IN_MAP;}}

export function App(){
 const [state,setState]=useState(load),[mapImage,setMapImage]=useState(loadMap),[mapName,setMapName]=useState(()=>loadMap()===BUILT_IN_MAP?'San Sebastián':'Converted map'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState('0-0'),[scavengers,setScavengers]=useState(0),[workers,setWorkers]=useState(1),[partyWorkers,setPartyWorkers]=useState(1),[building,setBuilding]=useState<BuildingType>('well'),[intelViewer,setIntelViewer]=useState(state.currentPlayerId);const canvas=useRef<HTMLCanvasElement>(null);
 const current=state.players[state.currentPlayerId],viewer=state.players[intelViewer]??current,event=state.currentEventId?state.cards[state.currentEventId]:undefined,card=current.currentCardId?state.cards[current.currentCardId]:undefined;
 const dispatch=(action:Action)=>{try{const next=applyAction(state,action);setState(next);localStorage.setItem(SAVE,JSON.stringify(next));setError('');setNotice(action.type==='replaceMap'?'Map converted successfully.':'');}catch(e){setError(e instanceof Error?e.message:String(e));setNotice('');}};
 const cols=Math.max(...state.tiles.map(t=>t.x))+1,rows=Math.max(...state.tiles.map(t=>t.y))+1,selectedTile=state.tiles.find(t=>t.id===selected);
 const allocation=getWorkerAllocation(state),activitiesLeft=Math.max(0,state.activityLimit-state.activityUsed),working=current.survivors-current.idlers,waterNeed=current.survivors+(state.weather==='heat'?working:0),foodNeed=current.survivors;
 const phaseAction=()=>{if(state.phase==='event')dispatch({type:'resolveEvent'});else if(state.phase==='declare')dispatch({type:'declareScavengers',count:scavengers});else if(state.phase==='card')dispatch({type:'resolvePlayerCard'});else if(state.phase==='production')dispatch({type:'produce'});else if(state.phase==='activities')dispatch({type:'endActivities'});else if(state.phase==='consumption')dispatch({type:'consumeAndEndTurn'});};
 const phaseLabel={event:'Resolve event',declare:'Confirm scavengers',card:'Resolve player card',production:'Run production',activities:'Finish activities',consumption:'Consume & end turn',gameOver:'Game over'}[state.phase];
 const onMap=async(file:File)=>{try{const dataUrl=await fileToDataUrl(file),img=new Image();img.src=dataUrl;await img.decode();const c=canvas.current!;c.width=img.width;c.height=img.height;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);dispatch({type:'replaceMap',terrain:imageDataToTerrain(ctx.getImageData(0,0,c.width,c.height).data,c.width,c.height)});setMapImage(dataUrl);setMapName(file.name);try{localStorage.setItem(MAP_SAVE,dataUrl);}catch{setNotice('Map converted. The image is too large for browser storage, so it will last for this session only.');}}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const reset=()=>{const s=createInitialState();setState(s);localStorage.setItem(SAVE,JSON.stringify(s));localStorage.removeItem(MAP_SAVE);setMapImage(BUILT_IN_MAP);setMapName('San Sebastián');setSelected('0-0');setError('');setNotice('New game started with the original San Sebastián map.');};
 const buildings=useMemo(()=>Object.entries(BUILDINGS).filter(([k])=>!['base','bridge'].includes(k)) as [BuildingType,typeof BUILDINGS[BuildingType]][],[]);
 return <main>
  <header><div><p className="eyebrow">POST-COLLAPSE STRATEGY</p><h1>Survivors</h1></div><div className="round">ROUND <strong>{state.round}</strong><span>{current.name}</span></div></header>
  <div className="sr-only" aria-live="polite">{error||notice}</div>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice">{notice}</div>}
  <section className="hud" aria-label={`${current.name} status and resources`}><div className="hud-owner"><span>ACTIVE REFUGE</span><strong>{current.name}</strong></div><Status emoji="🧑‍🤝‍🧑" label="Survivors" value={current.survivors}/><Status emoji="🩹" label="Wounded" value={current.wounded}/><Status emoji="🪑" label="Idle" value={current.idlers}/><Status emoji="🎒" label="Scavengers" value={current.scavengers}/>{RESOURCE_KEYS.map(r=><Status key={r} emoji={RESOURCE_META[r].emoji} label={RESOURCE_META[r].label} value={current.resources[r]}/>) }<div className="hud-activity" title="Activities used and available"><span>⚡ Activities</span><strong>{state.activityUsed}/{state.activityLimit}</strong></div></section>
  <TurnTimeline state={state}/>
  <section className="layout"><div className="board-panel">
   <div className="map-title"><div><p className="eyebrow">FIELD MAP · {cols} × {rows}</p><h2>{mapName}</h2><p>Real-world map with tactical terrain overlay</p></div><label className="upload">Convert another map<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&onMap(e.target.files[0])}/></label></div>
   <div className="board" aria-label={`${mapName} terrain board, ${cols} columns by ${rows} rows`} style={{gridTemplateColumns:`repeat(${cols},1fr)`,gridTemplateRows:`repeat(${rows},1fr)`,aspectRatio:`${cols}/${rows}`,backgroundImage:`linear-gradient(#0001,#0001), url("${mapImage}")`}}>{state.tiles.map(t=>{const party=state.parties.find(p=>p.tileId===t.id);return <button key={t.id} type="button" aria-pressed={selected===t.id} aria-label={`${t.id}, ${TERRAIN[t.terrain].label}${t.buildings.length?`, ${t.buildings.map(b=>BUILDINGS[b.type].label).join(', ')}`:''}${party?`, party with ${party.survivors} survivors`:''}`} title={`${t.id} · ${TERRAIN[t.terrain].label}`} className={`tile ${selected===t.id?'selected':''}`} onClick={()=>setSelected(t.id)}><span className="terrain-icon" aria-hidden="true">{TERRAIN_EMOJI[t.terrain]}</span><span className="markers">{t.buildings.map(b=><span className={`building-marker ${b.readyRound>state.round?'constructing':''}`} key={b.id} title={BUILDINGS[b.type].label}><img src={`/icons/${b.type}.png`} alt=""/></span>)}{party&&<span className="party-marker" title={`${party.survivors} survivors in party`}>🚶<b>{party.survivors}</b></span>}</span></button>})}</div>
   <div className="legend" aria-label="Terrain legend">{Object.entries(TERRAIN_EMOJI).map(([k,emoji])=><span key={k} title={TERRAIN[k as Terrain].label}><b aria-hidden="true">{emoji}</b>{TERRAIN[k as Terrain].label}</span>)}</div>
  </div><aside>
   <WorkerPanel allocation={allocation}/>
   <div className="phase current-controls"><span>NOW · {current.name}</span><h2>{state.phase==='gameOver'?'GAME OVER':STEPS.find(x=>x.id===state.phase)?.label}</h2><p className="guidance"><strong>Now:</strong> {nowText(state,activitiesLeft,waterNeed,foodNeed)}<br/><strong>Next:</strong> {nextText(state)}</p>{state.phase==='event'&&event&&<CardView title="WORLD EVENT" name={event.name} text={event.description}/>} {state.phase==='card'&&card&&<CardView title="PLAYER CARD" name={card.name} text={card.description}/>} {state.phase==='declare'&&<label>Active scavengers<input type="number" min="0" max={allocation.idle} value={scavengers} onChange={e=>setScavengers(+e.target.value)}/></label>}<button className="primary" disabled={state.phase==='gameOver'} onClick={phaseAction}>{phaseLabel}</button></div>
   {state.phase==='activities'&&<div className="actions current-controls"><h3>Activities <small>{activitiesLeft} left</small></h3><p>Selected: {selectedTile?`${TERRAIN[selectedTile.terrain].label} ${selected}`:'none'}. Gather beside your base or via a ready adjacent gathering building.</p>{current.pendingFoundBuilding&&<button className="found" onClick={()=>dispatch({type:'placeFoundBuilding',tileId:selected})}>Place free {BUILDINGS[current.pendingFoundBuilding].label}</button>}<label>Workers (1–3)<input type="number" min="1" max="3" value={workers} onChange={e=>setWorkers(+e.target.value)}/></label><button onClick={()=>dispatch({type:'gather',tileId:selected,survivors:workers})}>Gather</button><button onClick={()=>dispatch({type:'lookForSurvivors',food:4})}>Search (4 food)</button><label>Structure<select value={building} onChange={e=>setBuilding(e.target.value as BuildingType)}>{buildings.map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><button onClick={()=>dispatch({type:'build',tileId:selected,building})}>Build</button><label>Party workers<input type="number" min="1" max={current.idlers} value={partyWorkers} onChange={e=>setPartyWorkers(+e.target.value)}/></label><button onClick={()=>dispatch({type:'createParty',survivors:partyWorkers})}>Form party</button>{state.parties.filter(x=>x.ownerId===current.id).map(p=><button key={p.id} onClick={()=>dispatch({type:'moveParty',partyId:p.id,tileId:selected})}>Move {p.id} ({p.survivors}) here</button>)}<label>Workshop output<select value={current.workshopOutput} onChange={e=>dispatch({type:'setWorkshopOutput',resource:e.target.value as 'tools'|'weapons'})}><option value="tools">5 tools</option><option value="weapons">5 weapons</option></select></label></div>}
   <div className="intel"><label>Intel viewer<select value={viewer.id} onChange={e=>setIntelViewer(e.target.value)}>{state.playerOrder.map(id=><option key={id} value={id}>{state.players[id].name}</option>)}</select></label><button disabled={viewer.resources.information<3} onClick={()=>dispatch({type:'peekNextCard',playerId:viewer.id,deck:'event'})}>Peek event · 3 info</button><button disabled={viewer.resources.information<3} onClick={()=>dispatch({type:'peekNextCard',playerId:viewer.id,deck:'player'})}>Peek player · 3 info</button>{Object.entries(state.peeks[viewer.id]??{}).map(([kind,id])=><CardView key={kind} title={`NEXT ${kind}`} name={state.cards[id].name} text={state.cards[id].description}/>)}</div>
  </aside></section>
  <section className="lower"><div><h3>Field log</h3>{state.log.slice(0,7).map((x,i)=><p key={i}>{x}</p>)}</div><div><h3>How this table works</h3><p>Pass the device to the named refuge. Resolve the phase button, then use activities on a selected tile. Faded structures are still under construction.</p><p>Seed <code>{state.seed}</code> · deterministic RNG <code>{state.rng}</code></p><button onClick={reset}>New game</button></div></section><canvas ref={canvas} hidden/>
 </main>;
}
function Status({emoji,label,value}:{emoji:string;label:string;value:number}){return <div className="status" title={`${label}: ${value}`} aria-label={`${label}: ${value}`}><span aria-hidden="true">{emoji}</span><strong>{value}</strong><small>{label}</small></div>}
function CardView({title,name,text}:{title:string;name:string;text:string}){return <article className="card"><span>{title}</span><h3>{name}</h3><p>{text}</p></article>}
function TurnTimeline({state}:{state:GameState}){const active=STEPS.findIndex(x=>x.id===state.phase),record=state.currentTurn;return <section className={`timeline ${state.phase==='gameOver'?'is-over':''}`} aria-label={`Round ${record.round}, ${state.players[record.playerId].name} turn timeline`}><div className="timeline-title"><div><span>ROUND {record.round} · TURN {record.turn}</span><h2>{state.players[record.playerId].name} plan</h2></div><p><b>{state.phase==='gameOver'?'Match ended':`Step ${active+1} of ${STEPS.length}`}</b> · select or focus a step for help</p></div><ol>{STEPS.map((step,index)=>{const status=state.phase==='gameOver'?'unavailable':index<active?'complete':index===active?'current':'upcoming',summary=stepSummary(step.id,record,state);return <li key={step.id} className={status}><details><summary aria-label={`${step.label}, ${status}. ${summary}`}><span className="step-icon" aria-hidden="true">{status==='complete'?'✓':step.icon}</span><span><b>{step.label}</b><small>{summary}</small></span></summary><div className="step-help" role="tooltip">{step.help}</div></details></li>})}</ol></section>}
function stepSummary(step:TurnStep,r:GameState['currentTurn'],state:GameState){if(step==='event')return r.event?(r.event.resolved?`${r.event.name}: ${r.event.description}`:`Reveal ${r.event.name}`):'No event card';if(step==='declare')return r.scavengers===undefined?'Choose how many go':`${r.scavengers} sent scavenging`;if(step==='card')return r.playerCard?`${r.playerCard.name}: ${r.playerCard.description}`:'Draw and resolve a card';if(step==='production')return r.production?resourceChanges(r.production)||'No resource change':'Ready structures produce';if(step==='activities')return r.activities.length?r.activities.map(x=>activityText(x,state)).join(' · '):state.phase==='activities'?`${Math.max(0,state.activityLimit-state.activityUsed)} activities remaining`:'Gather, build, search, parties';if(step==='consumption')return r.consumption?`${r.consumption.waterNeed} water, ${r.consumption.foodNeed} food, ${r.consumption.medicinesUsed}/${r.consumption.medicinesNeed} medicine${r.consumption.deaths?`; ${r.consumption.deaths} died`:''}`:`Needs ${state.players[r.playerId].survivors} food + water`;return ''}
function resourceChanges(xs:{resource:Resource;amount:number}[]){return xs.map(x=>`${x.amount>0?'+':''}${x.amount} ${RESOURCE_META[x.resource].label.toLowerCase()}`).join(', ')}
function activityText(x:TurnActivity,state:GameState){switch(x.type){case'gather':return `${x.survivors} gathered at ${TERRAIN[x.terrain].label} ${x.tileId} (${resourceChanges(x.gains)})`;case'build':return `${x.survivors} building ${BUILDINGS[x.building].label} at ${x.tileId}, ready round ${x.readyRound}`;case'foundBuilding':return `Found ${BUILDINGS[x.building].label} placed at ${x.tileId}, ready round ${x.readyRound}`;case'survivors':return `Found ${x.found} survivor${x.found===1?'':'s'} for ${x.food} food`;case'partyCreated':return `Party ${x.partyId} formed with ${x.survivors} at ${x.tileId}`;case'partyMoved':return `Party ${x.partyId} moved ${x.distance} tile${x.distance===1?'':'s'} to ${x.tileId}`;case'intel':return `${state.players[x.playerId].name} peeked at next ${x.deck} card: ${state.cards[x.cardId]?.name??x.cardId}`}}
function WorkerPanel({allocation:a}:{allocation:ReturnType<typeof getWorkerAllocation>}){const rows=[['🩹','Wounded / unavailable',a.wounded],['🎒','Scavenging',a.scavenging],['🪑','Idle / available',a.idle],['🛠️','Used this turn',a.usedThisTurn],['🚶','Attack parties',a.parties]] as const;return <section className="workers"><div><span>WORKER STATUS</span><strong>{a.accounted}/{a.total} accounted for</strong></div><ul>{rows.map(([icon,label,value])=><li key={label}><span aria-hidden="true">{icon}</span><b>{value}</b><small>{label}</small></li>)}</ul><p>Gathering and construction crews are “used this turn”; only attack parties keep a map position.</p></section>}
function nowText(state:GameState,left:number,water:number,food:number){switch(state.phase){case'event':return 'Resolve the shared world event.';case'declare':return 'Choose from the idle survivors shown above.';case'card':return 'Resolve this refuge’s player card.';case'production':return 'Collect output from ready structures.';case'activities':return `Choose map actions or finish; ${left} activit${left===1?'y':'ies'} remain.`;case'consumption':return `Prepare ${water} water, ${food} food, and medicine for each wound.`;default:return 'No further actions are available.'}}
function nextText(state:GameState){switch(state.phase){case'event':return 'Declare scavengers for the active refuge.';case'declare':return 'Draw and resolve its player card.';case'card':return 'Run automatic structure production.';case'production':return 'Spend the available activities on the map.';case'activities':return 'Consume supplies and hand off the device.';case'consumption':return state.currentPlayerId===state.playerOrder.at(-1)?'Start a new round with a world event.':'Pass to the next refuge for scavenger declaration.';default:return 'Start a new game when ready.'}}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error||new Error('Could not read map image.'));reader.readAsDataURL(file);});}
